### ISSUE TITLE
app/models/cart.rb model test missing one line

### ISSUE THREAD

**Issue by KieraAllen** [KieraAllen/monster_shop_2008#74]
After running `bundle exec rspec spec/models`, and then `open coverage/index.html`, we are missing testing this line ` @contents.delete(item_id)` in the `cart.rb` method `remove_item`.

I think that is a method that came with our code in the beginning, but we should probably make a model test at some point.

**Comment by stillsheryl** [comment]
Nice catch @KieraAllen! We fixed this by removing one more item so the cart moved to 0 items.
