### ISSUE TITLE
User can edit and delete items on heroku

### ISSUE THREAD

**Issue by stillsheryl** [KieraAllen/monster_shop_2008#77]
I expect that only merchants/admins should be able to have this functionality

![Screen Shot 2020-11-03 at 2 10 43 PM](https://user-images.githubusercontent.com/7945439/98040964-6dfa5680-1dde-11eb-833c-5e35ef7d77b2.png)

**Comment by KieraAllen** [comment]
We've discussed that this was a curious feature of the project (a regular user can delete items?), but determined that the user stories detailed it this way, so we can leave it and bring it up during project evals.
