### ISSUE TITLE
Top and Bottom 5 not showing on Heroku, but pass in tests

### ISSUE THREAD

**Issue by stillsheryl** [KieraAllen/monster_shop_2008#78]
![Screen Shot 2020-11-03 at 2 12 03 PM](https://user-images.githubusercontent.com/7945439/98041089-9da95e80-1dde-11eb-9491-3883c42e93ad.png)

**Comment by KieraAllen** [comment]
Is this because "we" haven't "bought" anything yet on Heroku?

**Comment by stillsheryl** [comment]
You were right! Added some orders and it's showing up now!
